### ISSUE TITLE
Serverless deploy error: Cannot read property 'classes' of undefined bug 

### ISSUE THREAD

**Issue by cedric-r-mycelium** [brefphp/bref#1426]
Description:

When I try to deploy my project I get this error when I run: serverless deploy

```
$ sls deploy --stage=prod
Running "serverless" from node_modules
Environment: linux, node 16.19.1, framework 3.27.0 (local) 3.27.0v (global), plugin 6.2.3, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Cannot resolve serverless.yml: Variables resolution errored with:
  - Cannot resolve variable at "provider.layers.1": TypeError: Cannot read properties of undefined (reading 'classes')
    at Object.resolve (/var/www/xxx/vendor/bref/extra-php-extensions/index.js:35:51)
    at async VariablesResolver.Object.defineProperties.memoizeMethods.resolveSource.d.normalizer.type.type (/var/www/xxx/node_modules/serverless/lib/configuration/variables/resolve.js:565:24)
    at async /var/www/xxx/node_modules/serverless/lib/configuration/variables/resolve.js:279:20
    at async VariablesResolver.resolveVariableSource (/var/www/xxx/node_modules/serverless/lib/configuration/variables/resolve.js:277:9)
    at async VariablesResolver.resolveVariable (/var/www/xxx/node_modules/serverless/lib/configuration/variables/resolve.js:194:24)
    at async /var/www/xxx/node_modules/serverless/lib/configuration/variables/resolve.js:118:9
    at async Promise.all (index 0)
    at async VariablesResolver.resolveVariables (/var/www/xxx/node_modules/serverless/lib/configuration/variables/resolve.js:112:5)
    at async VariablesResolver.self (/var/www/xxx/node_modules/serverless/lib/configuration/variables/resolve.js:461:9)
    at async Promise.all (index 1)
    at async /var/www/xxx/node_modules/serverless/scripts/serverless.js:754:9
    at async /var/www/xxx/node_modules/serverless/scripts/serverless.js:610:7,
```

```provider:
    name: aws
    timeout: 840
    region: eu-west-1
    runtime: provided.al2
    logs:
        frameworkLambda: true
    layers:
        - ${bref:layer.php-74} # PHP runtime
        - ${bref-extra:redis-php-74} # redis Extension
        - ${bref-extra:gd-php-74} # GD extension
        - ${bref-extra:imagick-php-74} # Imagick extension
```

Can someone help me on this?

**Comment by cedric-r-mycelium** [comment]
no error with` "bref/extra-php-extensions": "^0.11.33",` only with `"bref/extra-php-extensions": "^0.12.4"`

**Comment by cedric-r-mycelium** [comment]
i found the source :( 
![image](https://user-images.githubusercontent.com/46491128/220891300-6375872f-bdef-4dd3-adad-bc5944fbeb82.png)

sory for this issue

**Comment by mnapoli** [comment]
👍
