### ISSUE TITLE
TypeError Handling Headers with FpmHandler

### ISSUE THREAD

**Issue by ukramer** [brefphp/bref#1539]
**Description:**

FpmHandler has a type error sometimes. We don't know the exact headers causing this issue. It seems that `$header` is an integer.

Error from Lambda's log:
```
{
    "errorType": "TypeError",
    "errorMessage": "str_replace(): Argument #3 ($subject) must be of type array|string, int given",
    "stack": [
        "#0 /var/task/App/vendor/bref/bref/src/Event/Http/FpmHandler.php(238): str_replace()",
        "#1 /var/task/App/vendor/bref/bref/src/Event/Http/FpmHandler.php(117): Bref\\Event\\Http\\FpmHandler->eventToFastCgiRequest()",
        "#2 /var/task/App/vendor/bref/bref/src/Event/Http/HttpHandler.php(25): Bref\\Event\\Http\\FpmHandler->handleRequest()",
        "#3 /var/task/App/vendor/bref/bref/src/Runtime/Invoker.php(29): Bref\\Event\\Http\\HttpHandler->handle()",
        "#4 /var/task/App/vendor/bref/bref/src/Runtime/LambdaRuntime.php(91): Bref\\Runtime\\Invoker->invoke()",
        "#5 /opt/bootstrap(55): Bref\\Runtime\\LambdaRuntime->processNextEvent()",
        "#6 {main}"
    ]
}
```

A simple casting of `$header` to string would probably solve the issue for us.

**How to reproduce:**

`curl -H "1:test" URL`

**Comment by mnapoli** [comment]
Thanks for the report, I'll try to look into it soon!

In the meantime if anyone is up for a PR, go for it ❤️

**Comment by starred-gijs** [comment]
We recently switched to use FPM on Lambda and we experience the same issue:
![Screenshot 2023-06-22 at 13 15 00](https://github.com/brefphp/bref/assets/42832118/87f1975c-92a0-4e75-9479-3a6e933f723f)

In the example above the header name is `20` (as integer) which does not really make sense, so this is either a malicious request, or something else is going wrong in earlier processing. I can create a PR for a simple string cast to make the error go away, but im also interested to investigate if this is actually more of a bug downstream... I will report back if I find something

**Comment by starred-gijs** [comment]
When I change the default test event api-gateway to add one additional header with a name of just numbers, the error is reproduced:
```json
{
  "body": "eyJ0ZXN0IjoiYm9keSJ9",
  "resource": "/{proxy+}",
  "path": "/path/to/resource",
  "httpMethod": "POST",
  "isBase64Encoded": true,
  "queryStringParameters": {
    "foo": "bar"
  },
  "multiValueQueryStringParameters": {
    "foo": [
      "bar"
    ]
  },
  "pathParameters": {
    "proxy": "/path/to/resource"
  },
  "stageVariables": {
    "baz": "qux"
  },
  "headers": {
    "234": "hello",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Accept-Encoding": "gzip, deflate, sdch",
    "Accept-Language": "en-US,en;q=0.8",
    "Cache-Control": "max-age=0",
    "CloudFront-Forwarded-Proto": "https",
    "CloudFront-Is-Desktop-Viewer": "true",
    "CloudFront-Is-Mobile-Viewer": "false",
    "CloudFront-Is-SmartTV-Viewer": "false",
    "CloudFront-Is-Tablet-Viewer": "false",
    "CloudFront-Viewer-Country": "US",
    "Host": "1234567890.execute-api.us-east-1.amazonaws.com",
    "Upgrade-Insecure-Requests": "1",
    "User-Agent": "Custom User Agent String",
    "Via": "1.1 08f323deadbeefa7af34d5feb414ce27.cloudfront.net (CloudFront)",
    "X-Amz-Cf-Id": "cDehVQoZnx43VYQb9j2-nvCh-9z396Uhbp027Y2JvkCPNLmGJHqlaA==",
    "X-Forwarded-For": "127.0.0.1, 127.0.0.2",
    "X-Forwarded-Port": "443",
    "X-Forwarded-Proto": "https"
  },
  "multiValueHeaders": {
    "234": [
      "hello"
    ],
    "Accept": [
      "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
    ],
    "Accept-Encoding": [
      "gzip, deflate, sdch"
    ],
    "Accept-Language": [
      "en-US,en;q=0.8"
    ],
    "Cache-Control": [
      "max-age=0"
    ],
    "CloudFront-Forwarded-Proto": [
      "https"
    ],
    "CloudFront-Is-Desktop-Viewer": [
      "true"
    ],
    "CloudFront-Is-Mobile-Viewer": [
      "false"
    ],
    "CloudFront-Is-SmartTV-Viewer": [
      "false"
    ],
    "CloudFront-Is-Tablet-Viewer": [
      "false"
    ],
    "CloudFront-Viewer-Country": [
      "US"
    ],
    "Host": [
      "0123456789.execute-api.us-east-1.amazonaws.com"
    ],
    "Upgrade-Insecure-Requests": [
      "1"
    ],
    "User-Agent": [
      "Custom User Agent String"
    ],
    "Via": [
      "1.1 08f323deadbeefa7af34d5feb414ce27.cloudfront.net (CloudFront)"
    ],
    "X-Amz-Cf-Id": [
      "cDehVQoZnx43VYQb9j2-nvCh-9z396Uhbp027Y2JvkCPNLmGJHqlaA=="
    ],
    "X-Forwarded-For": [
      "127.0.0.1, 127.0.0.2"
    ],
    "X-Forwarded-Port": [
      "443"
    ],
    "X-Forwarded-Proto": [
      "https"
    ]
  },
  "requestContext": {
    "accountId": "123456789012",
    "resourceId": "123456",
    "stage": "prod",
    "requestId": "c6af9ac6-7b61-11e6-9a41-93e8deadbeef",
    "requestTime": "09/Apr/2015:12:34:56 +0000",
    "requestTimeEpoch": 1428582896000,
    "identity": {
      "cognitoIdentityPoolId": null,
      "accountId": null,
      "cognitoIdentityId": null,
      "caller": null,
      "accessKey": null,
      "sourceIp": "127.0.0.1",
      "cognitoAuthenticationType": null,
      "cognitoAuthenticationProvider": null,
      "userArn": null,
      "userAgent": "Custom User Agent String",
      "user": null
    },
    "path": "/prod/path/to/resource",
    "resourcePath": "/{proxy+}",
    "httpMethod": "POST",
    "apiId": "1234567890",
    "protocol": "HTTP/1.1"
  }
}
```
has extra header with name "234" will throw this error:
```json
{
  "errorType": "TypeError",
  "errorMessage": "str_replace(): Argument #3 ($subject) must be of type array|string, int given",
  "stackTrace": [
    "#0 /var/task/vendor/bref/bref/src/FpmRuntime/FpmHandler.php(251): str_replace('-', '_', 234)"
  ]
}
```

I will try to figure out where exactly this conversion happens

**Comment by mnapoli** [comment]
Thanks for investigating! That sounds a lot like a native PHP behavior 😬

https://3v4l.org/JuEQG

I think we should just force-cast to string

**Comment by starred-gijs** [comment]
Yes I can confirm this is native PHP behaviour. I will create a PR
