### ISSUE TITLE
Cannot run either Laravel Queue and Octane with 2.1.6

### ISSUE THREAD

**Issue by Adesin-fr** [brefphp/bref#1684]
New error since 2.1.6.

Complete Error from bref dashboard : 
```
{
  "errorType": "Error",
  "errorMessage": "Object of type Bref\\LaravelBridge\\Queue\\QueueHandler is not callable",
  "stack": [
    "#0 /var/task/vendor/bref/bref/src/Runtime/Invoker.php(29): Bref\\FunctionRuntime\\Main::Bref\\FunctionRuntime\\{closure}(Array, Object(Bref\\Context\\Context))",
    "#1 /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php(89): Bref\\Runtime\\Invoker->invoke(Object(Closure), Array, Object(Bref\\Context\\Context))",
    "#2 /var/task/vendor/bref/bref/src/FunctionRuntime/Main.php(39): Bref\\Runtime\\LambdaRuntime->processNextEvent(Object(Closure))",
    "#3 /opt/bref/bootstrap.php(17): Bref\\FunctionRuntime\\Main::run()",
    "#4 {main}"
  ]
}
```

I've tested with an empty project and can reproduce the error (with Octane Handler)

Here is the repo with a demo empty laravel project which fails when you try to access the API endpoint : https://github.com/Adesin-fr/Bref-Failing-Project

Had to revert back to 2.1.5 to get my projects running again.

**Comment by mnapoli** [comment]
Thanks, fixed by https://github.com/brefphp/bref/releases/tag/2.1.7
