### ISSUE TITLE
Throw an exception if event is not provided

### ISSUE THREAD

**Issue by linuxjuggler** [brefphp/bref#394]
In the default function file which is generated by bref the code is something like this

```php
<?php declare(strict_types=1);

require __DIR__.'/vendor/autoload.php';

lambda(function (array $event) {
    return 'Hello ' . ($event['name'] ?? 'world');
});

```

and executing the following local command works like a charm 

```shell
serverless invoke local --docker -f function --data '{"name": "Jane"}'
```

but if the user didn't supply the data argument 

```shell
serverless invoke local --docker -f function
```

the system will throw the following exception 

```shell
Fatal error: Argument 1 passed to {closure}() must be of the type array, string given, called in /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php on line 92 in /var/task/index.php:7
Stack trace:
#0 /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php(92): {closure}('', Object(Bref\Context\Context))
#1 /var/task/vendor/bref/bref/src/functions.php(17): Bref\Runtime\LambdaRuntime->processNextEvent(Object(Closure))
#2 /var/task/index.php(9): lambda(Object(Closure))
#3 {main}
```

To solve the issue we can do either:

1. remove the `$event` from the closure by default and instruct the user to add it when needed, like what is done for the `$context`
2. Validate the data passed to the function in the run time file `https://github.com/brefphp/bref/blob/master/src/Runtime/LambdaRuntime.php#L86`, adding something like this

```php
    public function processNextEvent(callable $handler): void
    {
        /** @var Context $context */
        [$event, $context] = $this->waitNextInvocation();

        if(!is_array($event) && empty($event)) {
            $event = [];
        }

        try {
            $this->sendResponse($context->getAwsRequestId(), $handler($event, $context));
        } catch (\Throwable $e) {
            $this->signalFailure($context->getAwsRequestId(), $e);
        }
    }
```

I am with the second option, and I am happy to do a small PR for any of the suggested solutions.

**Comment by mnapoli** [comment]
Thanks, that is a very good point!

Option 1 would work but it would make the "developer experience" a little bit worse.

Option 2 is interesting, however I would like to keep the behavior predictable. What I mean is that if an empty event is submitted, then it should be `null`, not an empty array (those are different things).

Maybe a 3rd option would be to remove the `array` type-hint from the default function?

After all, I don't think the event _must_ be an array 🤔 It could very well be `null`, an `int` or a `string`. Or maybe I'm wrong?

**Comment by linuxjuggler** [comment]
Here is the full log, not just the exception (forget about the numbering as we are talking about the same function, I just committed my validation hack which altered the line numbers)

```shell
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Building Docker image...
START RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72 Version: $LATEST

Fatal error: Argument 1 passed to {closure}() must be of the type array, string given, called in /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php on line 96 in /var/task/index.php:10
Stack trace:
#0 /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php(96): {closure}('', Object(Bref\Context\Context))
#1 /var/task/vendor/bref/bref/src/functions.php(17): Bref\Runtime\LambdaRuntime->processNextEvent(Object(Closure))
#2 /var/task/index.php(28): lambda(Object(Closure))
#3 {main}
END RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72
REPORT RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72  Init Duration: 359.21 ms        Duration: 41.01 ms      Billed Duration: 100 ms Memory Size: 1536 MB    Max Memory Used: 26 MB  
{
  "errorType": "TypeError",
  "errorMessage": "Argument 1 passed to {closure}() must be of the type array, string given, called in /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php on line 96",
  "stackTrace": [
    "#0 /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php(96): {closure}('', Object(Bref\\Context\\Context))",
    "#1 /var/task/vendor/bref/bref/src/functions.php(17): Bref\\Runtime\\LambdaRuntime-\u003eprocessNextEvent(Object(Closure))",
    "#2 /var/task/index.php(28): lambda(Object(Closure))",
    "#3 {main}"
  ]
}


/Users/zaher/.nvm/versions/node/v11.15.0/lib/node_modules/serverless/lib/classes/Error.js:94
    throw new Error(inspect(e));
          ^
Error: 1
    at process.module.exports.logError.e (/Users/zaher/.nvm/versions/node/v11.15.0/lib/node_modules/serverless/lib/classes/Error.js:94:11)
    at process.emit (events.js:193:13)
    at process.emit (/Users/zaher/.nvm/versions/node/v11.15.0/lib/node_modules/serverless/node_modules/source-map-support/source-map-support.js:465:21)
    at /Users/zaher/.nvm/versions/node/v11.15.0/lib/node_modules/serverless/node_modules/bluebird/js/release/debuggability.js:199:33
    at activeFireEvent (/Users/zaher/.nvm/versions/node/v11.15.0/lib/node_modules/serverless/node_modules/bluebird/js/release/debuggability.js:242:44)
    at fireRejectionEvent (/Users/zaher/.nvm/versions/node/v11.15.0/lib/node_modules/serverless/node_modules/bluebird/js/release/debuggability.js:632:14)
    at Promise._notifyUnhandledRejection (/Users/zaher/.nvm/versions/node/v11.15.0/lib/node_modules/serverless/node_modules/bluebird/js/release/debuggability.js:65:9)
    at Timeout._onTimeout (/Users/zaher/.nvm/versions/node/v11.15.0/lib/node_modules/serverless/node_modules/bluebird/js/release/debuggability.js:44:14)
    at listOnTimeout (internal/timers.js:535:17)
    at processTimers (internal/timers.js:479:7)
```

and it seemes that removing the array type hint from the closure fixed the issue

```php
<?php declare(strict_types=1);

require __DIR__.'/vendor/autoload.php';

lambda(function ($event) {
    return 'Hello ' . ($event['name'] ?? 'world');
});
```

```shell
➜  bref serverless invoke local --docker -f function
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Building Docker image...
START RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72 Version: $LATEST

"Hello world"

END RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72
REPORT RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72  Init Duration: 230.00 ms        Duration: 128.17 ms     Billed Duration: 200 ms Memory Size: 1536 MB    Max Memory Used: 25 MB  

```

**Comment by mnapoli** [comment]
OK good to know, let's do this then.

We need to change this line:

https://github.com/brefphp/bref/blob/ed5cbf0d7a8d7db7927981192892da014b68479c/template/default/index.php#L5

to remove the `array` type-hint.

**Comment by mnapoli** [comment]
Oh and let's also edit the documentation here to remove the type-hint in the examples as well: https://github.com/brefphp/bref/blob/master/docs/runtimes/function.md

**Comment by linuxjuggler** [comment]
I'll create a PR and push it for approval.
