### ISSUE TITLE
When i try to call my lambada i get server error 

### ISSUE THREAD

**Issue by ahmadmarafa** [brefphp/bref#558]
i'm getting this error

START RequestId: 716f09fa-f6bd-46b9-a9c5-6519e105385d Version: $LATEST
2020-02-15T10:06:24.633Z	716f09fa-f6bd-46b9-a9c5-6519e105385d	INFO	[STDERR] php: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory

2020-02-15T10:06:24.633Z	716f09fa-f6bd-46b9-a9c5-6519e105385d	ERROR	Invoke Error 	{"errorType":"Error","errorMessage":"PHP exit code: 127","stack":["Error: PHP exit code: 127","    at ChildProcess.<anonymous> (/var/task/handler.js:60:22)","    at ChildProcess.emit (events.js:223:5)","    at maybeClose (internal/child_process.js:1021:16)","    at Socket.<anonymous> (internal/child_process.js:430:11)","    at Socket.emit (events.js:223:5)","    at Pipe.<anonymous> (net.js:664:12)"]}
END RequestId: 716f09fa-f6bd-46b9-a9c5-6519e105385d
REPORT RequestId: 716f09fa-f6bd-46b9-a9c5-6519e105385d	Duration: 4.66 ms	Billed Duration: 100 ms	Memory Size: 1024 MB	Max Memory Used: 73 MB

**Comment by mnapoli** [comment]
The `/var/task/handler.js` file makes me think that a very old version of Bref was installed by Composer. This is probably because you are using an outdated PHP version. Bref requires PHP 7.2 or greater.

Let me know if there are still problems after upgrading PHP and reinstalling Bref.
