### ISSUE TITLE
Following first step tutorial failed with Call to Undefined stream_isatty() error 

### ISSUE THREAD

**Issue by monaye** [brefphp/bref#563]
Just started out with Bref and got following after running the `vendor/bin/bref init` 

```
mowin:breffunc mowin$ composer require bref/bref
Using version ^0.5.15 for bref/bref
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 21 installs, 0 updates, 0 removals
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing psr/http-server-handler (1.0.1): Loading from cache
  - Installing riverline/multipart-parser (2.0.8): Loading from cache
  - Installing hollodotme/fast-cgi-client (v3.0.1): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.14.0): Loading from cache
  - Installing mtdowling/jmespath.php (2.5.0): Loading from cache
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing ralouphie/getallheaders (3.0.3): Loading from cache
  - Installing guzzlehttp/psr7 (1.6.1): Loading from cache
  - Installing guzzlehttp/guzzle (6.5.2): Loading from cache
  - Installing aws/aws-sdk-php (3.133.17): Loading from cache
  - Installing symfony/process (v5.0.4): Loading from cache
  - Installing symfony/polyfill-ctype (v1.14.0): Loading from cache
  - Installing symfony/filesystem (v5.0.4): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing php-di/invoker (2.0.0): Loading from cache
  - Installing symfony/service-contracts (v2.0.1): Loading from cache
  - Installing symfony/polyfill-php73 (v1.14.0): Loading from cache
  - Installing symfony/console (v5.0.4): Loading from cache
  - Installing mnapoli/silly (1.7.2): Loading from cache
  - Installing bref/bref (0.5.15): Loading from cache
guzzlehttp/psr7 suggests installing zendframework/zend-httphandlerrunner (Emit PSR-7 responses)
guzzlehttp/guzzle suggests installing psr/log (Required for using the Log middleware)
aws/aws-sdk-php suggests installing doctrine/cache (To use the DoctrineCacheAdapter)
aws/aws-sdk-php suggests installing aws/aws-php-sns-message-validator (To validate incoming SNS notifications)
symfony/service-contracts suggests installing symfony/service-implementation
symfony/console suggests installing symfony/event-dispatcher
symfony/console suggests installing symfony/lock
symfony/console suggests installing psr/log (For using the console logger)
Writing lock file
Generating autoload files
mowin:breffunc mowin$
mowin:breffunc mowin$
mowin:breffunc mowin$ vendor/bin/bref init

Fatal error: Uncaught Error: Call to undefined function Symfony\Component\Console\Output\stream_isatty() in /Users/mowin/Documents/000_APPS/playground/breffunc/vendor/symfony/console/Output/StreamOutput.php:117
Stack trace:
#0 /Users/mowin/Documents/000_APPS/playground/breffunc/vendor/symfony/console/Output/StreamOutput.php(52): Symfony\Component\Console\Output\StreamOutput->hasColorSupport()
#1 /Users/mowin/Documents/000_APPS/playground/breffunc/vendor/symfony/console/Output/ConsoleOutput.php(42): Symfony\Component\Console\Output\StreamOutput->__construct(Resource id #64, 32, NULL, NULL)
#2 /Users/mowin/Documents/000_APPS/playground/breffunc/vendor/symfony/console/Application.php(119): Symfony\Component\Console\Output\ConsoleOutput->__construct()
#3 /Users/mowin/Documents/000_APPS/playground/breffunc/vendor/bref/bref/bref(423): Symfony\Component\Console\Application->run()
#4 {main}
  thrown in /Users/mowin/Documents/000_APPS/playground/breffunc/vendor/symfony/console/Output/StreamOutput.php on line 117
mowin:breffunc mowin$
```

**Comment by mnapoli** [comment]
It seems to be a bug with the Symfony Console.

I found this pull request: https://github.com/symfony/symfony/pull/33878/files#diff-4bcd3012b1219ba0a2a8bda037dd6743L112-L122 It seems to be introducing the error you get.

> stream_isatty is always available since PHP 7.2, which is the minimal version required for Symfony 5.0

Which version of PHP do you have? What is your OS? How did you install PHP?

**Comment by ArtemYurov** [comment]
MacBook-Air:~ artem$ php -v
PHP 7.3.7 (cli) (built: Jul 16 2019 16:30:30) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.7, Copyright (c) 1998-2018 Zend Technologies
MacBook-Air:~ artem$ laravel
PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\Console\Output\stream_isatty() in /Users/artem/.composer/vendor/symfony/console/Output/StreamOutput.php:117
Stack trace:
#0 /Users/artem/.composer/vendor/symfony/console/Output/StreamOutput.php(52): Symfony\Component\Console\Output\StreamOutput->hasColorSupport()
#1 /Users/artem/.composer/vendor/symfony/console/Output/ConsoleOutput.php(42): Symfony\Component\Console\Output\StreamOutput->__construct(Resource id #70, 32, NULL, NULL)
#2 /Users/artem/.composer/vendor/symfony/console/Application.php(118): Symfony\Component\Console\Output\ConsoleOutput->__construct()
#3 /Users/artem/.composer/vendor/laravel/installer/bin/laravel(13): Symfony\Component\Console\Application->run()
#4 {main}
  thrown in /Users/artem/.composer/vendor/symfony/console/Output/StreamOutput.php on line 117
MacBook-Air:~ artem$

**Comment by mnapoli** [comment]
Given the little information I have, I encourage you to open an issue in the Symfony project.

**Comment by ArtemYurov** [comment]
Sorry. I change code to old and see this:
Problem 1
    - This package requires php ^7.2.5 but your PHP version (7.1.23) does not satisfy that requirement.

when i start laravel it's use incorrect version of PHP

**Comment by mnapoli** [comment]
@ArtemYurov the error message tells you have a an old version of PHP. You need to upgrade it.
