### ISSUE TITLE
Did you succeed with opcache.preload?

### ISSUE THREAD

**Issue by shouze** [brefphp/bref#719]
I've tried to deploy some Symfony based Lambda with Bref with [preloading enabled](https://symfony.com/index.php/doc/current/performance.html#use-the-opcache-class-preloading).

When using `opcache.preload=/var/task/var/cache/prod/App_KernelProdContainer.preload.php` a I get this:
![image](https://user-images.githubusercontent.com/54712/90179082-35ce1380-ddad-11ea-93aa-4d4c1a0bd8ed.png)

This has been discussed a bit more than one year ago: https://github.com/brefphp/bref/issues/100#issuecomment-443544253

I've also tried the variant with `opcache.preload=/tmp/cache/prod/App_KernelProdContainer.preload.php` where I copy the cache and it's not working.

So I wonder if anybody has tried and succeed? :thinking:

**Comment by shouze** [comment]
@Nyholm I've just seen your article, given the path in the post (/var/task/...) did you test in a lambda?

**Comment by Nyholm** [comment]
Yes, I made it work. It gave me some performance improvement. But I don't currently run in in prod because at the time I didnt have a ["make sure the new deployment work"-script](https://github.com/Happyr/bref-hook-handler). 

What is on line 409 in your preload file?

**Comment by shouze** [comment]
@Nyholm sorry for the late answer, I don't know if it can help but on line 409 this is the call to `Preloader::preload`
![image](https://user-images.githubusercontent.com/54712/90436904-c10f1800-e0d1-11ea-928d-620bf951d604.png)

(I have a lot of preloaded classes at the moment, I expect reducing by 10-20%)

**Comment by shouze** [comment]
For the information, I'm running latest php 7.4 with latest bref and Symfony 5.1

**Comment by shouze** [comment]
And here's a more detailed log output:
```log
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|   timestamp   |                                                                                                message                                                                                                 |
|---------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1597692720025 | Mon Aug 17 19:32:00 2020 (7): [Debug] APM: disabling for CLI                                                                                                                                           |
| 1597692720077 | Mon Aug 17 19:32:00 2020 (9): [Debug] APM: disabled                                                                                                                                                    |
| 1597692720077 | Mon Aug 17 19:32:00 2020 (9): [Info] pgsql extension is not loaded, Blackfire SQL analyzer will be disabled for pgsql SQL queries                                                                      |
| 1597692720077 | Mon Aug 17 19:32:00 2020 (9): [Info] oci8 extensions is not loaded, Blackfire SQL analyzer will be disabled for oci SQL queries                                                                        |
| 1597692720180 | [17-Aug-2020 19:32:00] NOTICE: PHP message: PHP Fatal error:  Uncaught ErrorException: PHP Startup: failed to open stream: No such file or directory in /var/task/vendor/composer/ClassLoader.php:444  |
| 1597692720180 | Stack trace:                                                                                                                                                                                           |
| 1597692720180 | #0 /var/task/vendor/composer/ClassLoader.php(444): Symfony\Component\DependencyInjection\Dumper\Preloader::Symfony\Component\DependencyInjection\Dumper\{closure}()                                    |
| 1597692720180 | #1 /var/task/vendor/composer/ClassLoader.php(444): include()                                                                                                                                           |
| 1597692720180 | #2 /var/task/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()                                                                                                                     |
| 1597692720180 | #3 [internal function]: Composer\Autoload\ClassLoader->loadClass()                                                                                                                                     |
| 1597692720180 | #4 [internal function]: spl_autoload_call()                                                                                                                                                            |
| 1597692720180 | #5 /var/task/vendor/symfony/dependency-injection/Dumper/Preloader.php(79): ReflectionClass->__construct()                                                                                              |
| 1597692720180 | #6 /var/task/vendor/symfony/dependency-injection/Dumper/Preloader.php(60): Symfony\Component\DependencyInjection\Dumper\Preloader::doPreload()                                                         |
| 1597692720180 | #7 /var/task/var/cache/prod/Gogaille_KernelProdContainer.preload.php(409): Symfony\Component\DependencyInjection\Dumper\Preloader::preload()                                                           |
| 1597692720180 | ...                                                                                                                                                                                                    |
| 1597692720185 | Error while starting PHP-FPM                                                                                                                                                                           |
| 1597692720185 | Fatal error: Exception: PHP-FPM failed to start in /var/task/vendor/bref/bref/src/Event/Http/FpmHandler.php:158                                                                                        |
| 1597692720185 | Stack trace:                                                                                                                                                                                           |
| 1597692720185 | #0 /var/task/vendor/bref/bref/src/Event/Http/FpmHandler.php(82): Bref\Event\Http\FpmHandler->waitUntilReady()                                                                                          |
| 1597692720185 | #1 /opt/bootstrap(29): Bref\Event\Http\FpmHandler->start()                                                                                                                                             |
| 1597692720240 | #2 {main}                                                                                                                                                                                              |
| 1597692720240 | END RequestId: 1c1b5a85-4301-49a6-b927-fcbf98fe2429                                                                                                                                                    |
| 1597692720240 | REPORT RequestId: 1c1b5a85-4301-49a6-b927-fcbf98fe2429 Duration: 234.12 ms Billed Duration: 300 ms Memory Size: 1024 MB Max Memory Used: 30 MB                                                         |
| 1597692720240 | Unknown application error occurred                                                                                                                                                                     |
| 1597692720277 | Mon Aug 17 19:32:00 2020 (8): [Debug] APM: disabled                                                                                                                                                    |
| 1597692720278 | Mon Aug 17 19:32:00 2020 (8): [Info] pgsql extension is not loaded, Blackfire SQL analyzer will be disabled for pgsql SQL queries                                                                      |
| 1597692720278 | Mon Aug 17 19:32:00 2020 (8): [Info] oci8 extensions is not loaded, Blackfire SQL analyzer will be disabled for oci SQL queries                                                                        |
| 1597692720278 | Mon Aug 17 19:32:00 2020 (8): [Debug] APM: disabling for CLI                                                                                                                                           |
| 1597692720314 | Mon Aug 17 19:32:00 2020 (9): [Debug] APM: disabled                                                                                                                                                    |
| 1597692720314 | Mon Aug 17 19:32:00 2020 (9): [Info] pgsql extension is not loaded, Blackfire SQL analyzer will be disabled for pgsql SQL queries                                                                      |
| 1597692720314 | Mon Aug 17 19:32:00 2020 (9): [Info] oci8 extensions is not loaded, Blackfire SQL analyzer will be disabled for oci SQL queries                                                                        |
| 1597692720374 | [17-Aug-2020 19:32:00] NOTICE: PHP message: PHP Fatal error:  Uncaught ErrorException: PHP Startup: failed to open stream: No such file or directory in /var/task/vendor/composer/ClassLoader.php:444  |
| 1597692720374 | Stack trace:                                                                                                                                                                                           |
| 1597692720374 | #0 /var/task/vendor/composer/ClassLoader.php(444): Symfony\Component\DependencyInjection\Dumper\Preloader::Symfony\Component\DependencyInjection\Dumper\{closure}()                                    |
| 1597692720374 | #1 /var/task/vendor/composer/ClassLoader.php(444): include()                                                                                                                                           |
| 1597692720374 | #2 /var/task/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()                                                                                                                     |
| 1597692720374 | #3 [internal function]: Composer\Autoload\ClassLoader->loadClass()                                                                                                                                     |
| 1597692720374 | #4 [internal function]: spl_autoload_call()                                                                                                                                                            |
| 1597692720374 | #5 /var/task/vendor/symfony/dependency-injection/Dumper/Preloader.php(79): ReflectionClass->__construct()                                                                                              |
| 1597692720374 | #6 /var/task/vendor/symfony/dependency-injection/Dumper/Preloader.php(60): Symfony\Component\DependencyInjection\Dumper\Preloader::doPreload()                                                         |
| 1597692720374 | #7 /var/task/var/cache/prod/Gogaille_KernelProdContainer.preload.php(409): Symfony\Component\DependencyInjection\Dumper\Preloader::preload()                                                           |
| 1597692720374 | ...                                                                                                                                                                                                    |
| 1597692720374 | Error while starting PHP-FPM                                                                                                                                                                           |
| 1597692720374 | Fatal error: Exception: PHP-FPM failed to start in /var/task/vendor/bref/bref/src/Event/Http/FpmHandler.php:158                                                                                        |
| 1597692720374 | Stack trace:                                                                                                                                                                                           |
| 1597692720374 | #0 /var/task/vendor/bref/bref/src/Event/Http/FpmHandler.php(82): Bref\Event\Http\FpmHandler->waitUntilReady()                                                                                          |
| 1597692720374 | #1 /opt/bootstrap(29): Bref\Event\Http\FpmHandler->start()                                                                                                                                             |
| 1597692720408 | #2 {main}                                                                                                                                                                                              |
| 1597692726001 | START RequestId: 086bf333-3bc3-4779-ac7e-ec84e2f7be39 Version: $LATEST                                                                                                                                 |
| 1597692726015 | Mon Aug 17 19:32:06 2020 (8): [Debug] APM: disabled                                                                                                                                                    |
| 1597692726016 | Mon Aug 17 19:32:06 2020 (8): [Info] pgsql extension is not loaded, Blackfire SQL analyzer will be disabled for pgsql SQL queries                                                                      |
| 1597692726016 | Mon Aug 17 19:32:06 2020 (8): [Info] oci8 extensions is not loaded, Blackfire SQL analyzer will be disabled for oci SQL queries                                                                        |
| 1597692726016 | Mon Aug 17 19:32:06 2020 (8): [Debug] APM: disabling for CLI                                                                                                                                           |
| 1597692726059 | Mon Aug 17 19:32:06 2020 (9): [Debug] APM: disabled                                                                                                                                                    |
| 1597692726059 | Mon Aug 17 19:32:06 2020 (9): [Info] pgsql extension is not loaded, Blackfire SQL analyzer will be disabled for pgsql SQL queries                                                                      |
| 1597692726059 | Mon Aug 17 19:32:06 2020 (9): [Info] oci8 extensions is not loaded, Blackfire SQL analyzer will be disabled for oci SQL queries                                                                        |
| 1597692726171 | [17-Aug-2020 19:32:06] NOTICE: PHP message: PHP Fatal error:  Uncaught ErrorException: PHP Startup: failed to open stream: No such file or directory in /var/task/vendor/composer/ClassLoader.php:444  |
| 1597692726171 | Stack trace:                                                                                                                                                                                           |
| 1597692726171 | #0 /var/task/vendor/composer/ClassLoader.php(444): Symfony\Component\DependencyInjection\Dumper\Preloader::Symfony\Component\DependencyInjection\Dumper\{closure}()                                    |
| 1597692726171 | #1 /var/task/vendor/composer/ClassLoader.php(444): include()                                                                                                                                           |
| 1597692726171 | #2 /var/task/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()                                                                                                                     |
| 1597692726171 | #3 [internal function]: Composer\Autoload\ClassLoader->loadClass()                                                                                                                                     |
| 1597692726171 | #4 [internal function]: spl_autoload_call()                                                                                                                                                            |
| 1597692726171 | #5 /var/task/vendor/symfony/dependency-injection/Dumper/Preloader.php(79): ReflectionClass->__construct()                                                                                              |
| 1597692726171 | #6 /var/task/vendor/symfony/dependency-injection/Dumper/Preloader.php(60): Symfony\Component\DependencyInjection\Dumper\Preloader::doPreload()                                                         |
| 1597692726171 | #7 /var/task/var/cache/prod/Gogaille_KernelProdContainer.preload.php(409): Symfony\Component\DependencyInjection\Dumper\Preloader::preload()                                                           |
| 1597692726171 | ...                                                                                                                                                                                                    |
| 1597692726178 | Error while starting PHP-FPM                                                                                                                                                                           |
| 1597692726178 | Fatal error: Exception: PHP-FPM failed to start in /var/task/vendor/bref/bref/src/Event/Http/FpmHandler.php:158                                                                                        |
| 1597692726178 | Stack trace:                                                                                                                                                                                           |
| 1597692726178 | #0 /var/task/vendor/bref/bref/src/Event/Http/FpmHandler.php(82): Bref\Event\Http\FpmHandler->waitUntilReady()                                                                                          |
| 1597692726178 | #1 /opt/bootstrap(29): Bref\Event\Http\FpmHandler->start()                                                                                                                                             |
| 1597692726223 | #2 {main}                                                                                                                                                                                              |
| 1597692726224 | END RequestId: 086bf333-3bc3-4779-ac7e-ec84e2f7be39                                                                                                                                                    |
| 1597692726224 | REPORT RequestId: 086bf333-3bc3-4779-ac7e-ec84e2f7be39 Duration: 220.54 ms Billed Duration: 300 ms Memory Size: 1024 MB Max Memory Used: 30 MB                                                         |
| 1597692726224 | Unknown application error occurred                                                                                                                                                                     |
| 1597692726260 | Mon Aug 17 19:32:06 2020 (8): [Debug] APM: disabled                                                                                                                                                    |
| 1597692726261 | Mon Aug 17 19:32:06 2020 (8): [Info] pgsql extension is not loaded, Blackfire SQL analyzer will be disabled for pgsql SQL queries                                                                      |
| 1597692726261 | Mon Aug 17 19:32:06 2020 (8): [Info] oci8 extensions is not loaded, Blackfire SQL analyzer will be disabled for oci SQL queries                                                                        |
| 1597692726261 | Mon Aug 17 19:32:06 2020 (8): [Debug] APM: disabling for CLI                                                                                                                                           |
| 1597692726289 | Mon Aug 17 19:32:06 2020 (9): [Debug] APM: disabled                                                                                                                                                    |
| 1597692726294 | Mon Aug 17 19:32:06 2020 (9): [Info] pgsql extension is not loaded, Blackfire SQL analyzer will be disabled for pgsql SQL queries                                                                      |
| 1597692726294 | Mon Aug 17 19:32:06 2020 (9): [Info] oci8 extensions is not loaded, Blackfire SQL analyzer will be disabled for oci SQL queries                                                                        |
| 1597692726354 | [17-Aug-2020 19:32:06] NOTICE: PHP message: PHP Fatal error:  Uncaught ErrorException: PHP Startup: failed to open stream: No such file or directory in /var/task/vendor/composer/ClassLoader.php:444  |
| 1597692726354 | Stack trace:                                                                                                                                                                                           |
| 1597692726354 | #0 /var/task/vendor/composer/ClassLoader.php(444): Symfony\Component\DependencyInjection\Dumper\Preloader::Symfony\Component\DependencyInjection\Dumper\{closure}()                                    |
| 1597692726354 | #1 /var/task/vendor/composer/ClassLoader.php(444): include()                                                                                                                                           |
| 1597692726354 | #2 /var/task/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()                                                                                                                     |
| 1597692726354 | #3 [internal function]: Composer\Autoload\ClassLoader->loadClass()                                                                                                                                     |
| 1597692726354 | #4 [internal function]: spl_autoload_call()                                                                                                                                                            |
| 1597692726354 | #5 /var/task/vendor/symfony/dependency-injection/Dumper/Preloader.php(79): ReflectionClass->__construct()                                                                                              |
| 1597692726354 | #6 /var/task/vendor/symfony/dependency-injection/Dumper/Preloader.php(60): Symfony\Component\DependencyInjection\Dumper\Preloader::doPreload()                                                         |
| 1597692726354 | #7 /var/task/var/cache/prod/Gogaille_KernelProdContainer.preload.php(409): Symfony\Component\DependencyInjection\Dumper\Preloader::preload()                                                           |
| 1597692726354 | ...                                                                                                                                                                                                    |
| 1597692726354 | Error while starting PHP-FPM                                                                                                                                                                           |
| 1597692726354 | Fatal error: Exception: PHP-FPM failed to start in /var/task/vendor/bref/bref/src/Event/Http/FpmHandler.php:158                                                                                        |
| 1597692726354 | Stack trace:                                                                                                                                                                                           |
| 1597692726354 | #0 /var/task/vendor/bref/bref/src/Event/Http/FpmHandler.php(82): Bref\Event\Http\FpmHandler->waitUntilReady()                                                                                          |
| 1597692726354 | #1 /opt/bootstrap(29): Bref\Event\Http\FpmHandler->start()                                                                                                                                             |
| 1597692726393 | #2 {main}                                                                                                                                                                                              |
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by shouze** [comment]
Ok so I had a first error because of a vendor file I was deleting during packaging, but after that I've discovered some other classes that were preloaded but missing. One of them was a suggested dependency of one of my production requirements ^^.

Instead of installing the suggested requirement I've tried to tag services that should use it as [`container.no_preload` but with no success at the moment](https://symfony.com/index.php/doc/current/reference/dic_tags.html#container-no-preload) as it's not that easy to find out every service dependency.

**Comment by shouze** [comment]
@Nyholm I've fixed everything now, thank your for your support :heart: .

I've found a way to override some unused dependency service to fix everything. Not the best thing but acceptable unless the dependency improves. So I close this issue, can be useful for other people that want to try/discuss about preload :wink:.

**Comment by wladimiravila** [comment]
@shouze Hello, did you remembered how to solve it? I got the same error on lambda aws, and php 8,1 -fpm

| 1597692726178 | Error while starting PHP-FPM                                                                                                                                                                           |
| 1597692726178 | Fatal error: Exception: PHP-FPM failed to start in /var/task/vendor/bref/bref/src/Event/Http/FpmHandler.php:158                                                                                        |
| 1597692726178 | Stack trace:                                                                                                                                                                                           |
| 1597692726178 | #0 /var/task/vendor/bref/bref/src/Event/Http/FpmHandler.php(82): Bref\Event\Http\FpmHandler->waitUntilReady()                                                                                          |
| 1597692726178 | #1 /opt/bootstrap(29): Bref\Event\Http\FpmHandler->start()

**Comment by Nyholm** [comment]
I have a file called `php/conf.d/preload.ini` which contains 

```
opcache.preload=/var/task/config/preload.php
```

It has been working for me since the first symfony version that supported preloading. 
Does it work for you locally?

**Comment by shouze** [comment]
> @shouze Hello, did you remember how to solve it? I got the almost the same error on lambda aws, and php 8,1 -fpm sf 6.3
> 
> ![Screen Shot 2023-07-07 at 12 51 32 AM](https://user-images.githubusercontent.com/1641715/251649586-93351832-43ed-46e8-9047-5f04f47bddbd.png)
> 
> Any comments or ideas about how to solve it?
> 
> regards!

I have to admit that everything works for me since a while. Should be the same for you. Any chance to upgrade to php 8.2 maybe?
