### ISSUE TITLE
SSL certificate problem: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by ilbonte** [brefphp/bref#758]
Hi, fist of work thank you for your work and your support :D 

My applications calls an external API (https://www.toggl.com/reports/api/v2) using Guzzle Client but i get the following error.

```
Invoke Error	{"errorType":"Guzzle\\Http\\Exception\\CurlException","errorMessage":"[curl] 60: SSL certificate problem: self signed certificate in certificate chain [url] https:\/\/www.toggl.com\/reports\/api\/v2\/details?......
```

Please note that locally the API call works

I suspect that it could be due to a root certificate mussing. Could this a problem related to bref/aws lambda?

We are using `"bref/bref": "^0.5.30"` and  this layer: `${bref:layer.php-73}`

Full stack trace: 

```
Invoke Error	{"errorType":"Guzzle\\Http\\Exception\\CurlException","errorMessage":"[curl] 60: SSL certificate problem: self signed certificate in certificate chain [url] https:\/\/www.toggl.com\/reports\/api\/v2\/details?.......","stack":[
    "#0 \/var\/task\/vendor\/guzzle\/guzzle\/src\/Guzzle\/Http\/Curl\/CurlMulti.php(292): Guzzle\\Http\\Curl\\CurlMulti->isCurlException(Object(Guzzle\\Http\\Message\\Request), Object(Guzzle\\Http\\Curl\\CurlHandle), Array)",
"#1 \/var\/task\/vendor\/guzzle\/guzzle\/src\/Guzzle\/Http\/Curl\/CurlMulti.php(257): Guzzle\\Http\\Curl\\CurlMulti->processResponse(Object(Guzzle\\Http\\Message\\Request), Object(Guzzle\\Http\\Curl\\CurlHandle), Array)",
"#2 \/var\/task\/vendor\/guzzle\/guzzle\/src\/Guzzle\/Http\/Curl\/CurlMulti.php(240): Guzzle\\Http\\Curl\\CurlMulti->processMessages()",
"#3 \/var\/task\/vendor\/guzzle\/guzzle\/src\/Guzzle\/Http\/Curl\/CurlMulti.php(224): Guzzle\\Http\\Curl\\CurlMulti->executeHandles()",
"#4 \/var\/task\/vendor\/guzzle\/guzzle\/src\/Guzzle\/Http\/Curl\/CurlMulti.php(111): Guzzle\\Http\\Curl\\CurlMulti->perform()",
"#5 \/var\/task\/vendor\/guzzle\/guzzle\/src\/Guzzle\/Http\/Curl\/CurlMultiProxy.php(94): Guzzle\\Http\\Curl\\CurlMulti->send()",
"#6 \/var\/task\/vendor\/guzzle\/guzzle\/src\/Guzzle\/Http\/Client.php(284): Guzzle\\Http\\Curl\\CurlMultiProxy->send()",
"#7 \/var\/task\/vendor\/guzzle\/guzzle\/src\/Guzzle\/Service\/Client.php(136): Guzzle\\Http\\Client->send(Object(Guzzle\\Http\\Message\\Request))",
"#8 \/var\/task\/vendor\/guzzle\/guzzle\/src\/Guzzle\/Service\/Command\/AbstractCommand.php(153): Guzzle\\Service\\Client->execute(Object(Guzzle\\Service\\Command\\OperationCommand))",
"#9 \/var\/task\/vendor\/guzzle\/guzzle\/src\/Guzzle\/Service\/Command\/AbstractCommand.php(189): Guzzle\\Service\\Command\\AbstractCommand->execute()",
"#10 \/var\/task\/vendor\/guzzle\/guzzle\/src\/Guzzle\/Service\/Client.php(76): Guzzle\\Service\\Command\\AbstractCommand->getResult()",
"#11 \/var\/task\/vendor\/ajt\/guzzle-toggl\/src\/AJT\/Toggl\/ReportsClient.php(74): Guzzle\\Service\\Client->__call('Details', Array)",
"#12 \/var\/task\/src\/Facade\/TogglFacade.php(26): AJT\\Toggl\\ReportsClient->__call('details', Array)",
"#13 \/var\/task\/src\/Entries\/EntryRepository.php(24): My\\Facade\\TogglFacade->getReport(Array)",
"#14 \/var\/task\/generate.php(17): My\\Entries\\EntryRepository->getEntriesByMonth('2020', '8')",
"#15 \/var\/task\/vendor\/bref\/bref\/src\/Runtime\/LambdaRuntime.php(109): {closure}(Array, Object(Bref\\Context\\Context))",
"#16 \/opt\/bref\/bootstrap.php(38): Bref\\Runtime\\LambdaRuntime->processNextEvent(Object(Closure))",
"#17 {main}"]}
```

**Comment by victormacko** [comment]
I'm guessing there might be a variation between the curl ssl on Lambda and what's setup on your local machine ... have you tried setting the guzzle SSL verification settings to disable the check you're hitting here?
Eg; http://docs.guzzlephp.org/en/stable/request-options.html#verify-option

**Comment by ilbonte** [comment]
Tried like that and also by specifying the ca certificate but with no luck

**Comment by ilbonte** [comment]
```
$cmd = 'curl -v -u d9de61f972edfc7xxxxxxx:api_token -X GET "https://www.toggl.com/reports/api/v2/details....."';
    var_dump(shell_exec( $cmd ));
```

and it worked :\

**Comment by mnapoli** [comment]
Honestly I'm not really sure how to help you 😕

**Comment by ilbonte** [comment]
We ended up not using guzzle-toggl and using guzzle to make the call directly. I don't think is a bref's problem

**Comment by mnapoli** [comment]
Thank you for the update.
