### ISSUE TITLE
Error: EIO: i/o error, open

### ISSUE THREAD

**Issue by qqjameqq1** [brefphp/bref#787]
Error --------------------------------------------------

Error: EIO: i/o error, open '/var/www/html/dentCoNew/api/src/vendor/aws/aws-sdk-php/src/data/sso/2019-06-10/paginators-1.json.php'
at Package.getFileContent (/home/laradock/.nvm/versions/node/v14.7.0/lib/node_modules/serverless/lib/plugins/package/lib/zipService.js:140:15)
at Package.getFileContentAndStat (/home/laradock/.nvm/versions/node/v14.7.0/lib/node_modules/serverless/lib/plugins/package/lib/zipService.js:129:12)
at Array.map ()
at WriteStream. (/home/laradock/.nvm/versions/node/v14.7.0/lib/node_modules/serverless/lib/plugins/package/lib/zipService.js:97:46)
at WriteStream.emit (events.js:314:20)
at WriteStream.EventEmitter.emit (domain.js:486:12)
at /var/www/html/dentCoNew/api/src/node_modules/@auth0/s3/node_modules/graceful-fs/graceful-fs.js:231:14
at /var/www/html/dentCoNew/api/src/node_modules/@auth0/s3/node_modules/graceful-fs/graceful-fs.js:258:16
at /home/laradock/.nvm/versions/node/v14.7.0/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:333:16
at FSReqCallback.oncomplete (fs.js:164:23)

Your Environment Information ---------------------------
Operating System: linux
Node Version: 14.7.0
Framework Version: 2.11.1
Plugin Version: 4.1.2
SDK Version: 2.3.2
Components Version: 3.3.1

**Comment by mnapoli** [comment]
Please provide more information.
