### ISSUE TITLE
Running locally using HttpRequestEvent fails with TypeError

### ISSUE THREAD

**Issue by sc0ttdav3y** [brefphp/bref#930]
**Description:**

When running locally with a `HttpRequestEvent` handler, Bref fails with a TypeError because `$event` is null but the method parameter type expects an array.

```
[ERROR] Argument 1 passed to Bref\Event\Http\HttpRequestEvent::__construct() must be of the type array, null given, called in /vendor/bref/bref/src/Event/Http/HttpHandler.php on line 23   
```

Relevant stack trace:

```
Stack trace:
#0 /vendor/bref/bref/src/Event/Http/HttpHandler.php(23): Bref\Event\Http\HttpRequestEvent->__construct(NULL)
#1 /vendor/bref/bref/src/Runtime/Invoker.php(29): Bref\Event\Http\HttpHandler->handle(NULL, Object(Bref\Context\Context))
#2 /vendor/bref/bref/src/Console/Command/Local.php(74): Bref\Runtime\Invoker->invoke(Object(Bref\Event\Http\Psr15Handler), NULL, Object(Bref\Context\Context))
#3 [internal function]: Bref\Console\Command\Local->__invoke(NULL, NULL, NULL, Object(Example\ApiTestString), NULL, Object(Symfony\Component\Console\Style\SymfonyStyle))
...

```

**How to reproduce:**

1. Implement a HttpRequestHandler 
2. Call via CLI as below

`Example\MyCommand.php`:

```php
<?php

namespace Example;

use Nyholm\Psr7\Response;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\RequestHandlerInterface;

class MyCommand implements RequestHandlerInterface
{
    final public function handle(ServerRequestInterface $request): ResponseInterface
    {
        return new Response(200, [], json_encode(["message" => "Hi"]));
    }
}
```

`handler.php`:
```php
<?php

require __DIR__ . '/vendor/autoload.php';
return new \Example\MyCommand();

```

Call it via CLI:

```
vendor/bin/bref local --handler=handler.php
```

**Comment by sc0ttdav3y** [comment]
I've submitted a PR that addresses this issue: https://github.com/brefphp/bref/pull/931

**Comment by mnapoli** [comment]
Closing per the PR
